### PR TITLE
Clippification

### LINKED ISSUE #10: Clippy
Since we are starting fresh, let's fix all the clippy lints and add it to the CI.

### PR DESCRIPTION
**Pull request by darosior**
This fixes *all* clippy warning from the whole repository. Some of them are... Well very opinionated to say the least. But to avoid bikeshedding i just applied all of them. Let's start fresh!

@edouardparis can you skim through the clippy fixes in the GUI folder? I checked the daemon one already.

Fixes #10.

### CODE REVIEW

**Comment by edouardparis** [comment]
rustfmt not happy
I am doing the same for gui: https://github.com/revault/minisafe/pull/61

**Comment by darosior** [comment]
> I am doing the same for gui: https://github.com/revault/minisafe/pull/61

As mentioned in the OP and in the title of the second commit this also fixes the GUI clippy warnings, that's why i pinged you actually:
> edouardparis can you skim through the clippy fixes in the GUI folder? I checked the daemon one already.

**Comment by darosior** [comment]
Force pushed to fixed rustfmt.

**Comment by darosior** [comment]
After discussion with Edouard, i've pushed a commit to enable clippy in the CI linters.

Also @edouardparis note the minor API break on the daemon side due to the change in enum variants.

**Review by edouardparis — APPROVED** [review]
ACK 7e911b8bb7ccca866db2afadb357615d3712a4cb

**Pull request merged**
