### PR TITLE
Add spend panel

### PR DESCRIPTION
**Pull request by edouardparis**
based on #71

### CODE REVIEW

**Comment by darosior** [comment]
Does this fix https://github.com/revault/minisafe/issues/34?

**Comment by edouardparis** [comment]
No am comparing psbt output script_pubkey with entered user addresses to find the one added by minisafed

**Comment by darosior** [comment]
Ok, nice. Does it mean we can close the issue then? Do you think we'll still need it eventually?

Keep in mind you can't rely on the ordering though. Unfortunately you *have* to walk through all the outputs of the transaction if you do that. It can still be `O(n)` if you make the addresses fed by the users in a HashMap though, so it should be acceptable for now.
------- Original Message -------

**Review by edouardparis — COMMENTED** [review]
Self-ACK 6f75515f9b572d6fa77facdba9ddd2cd1bf94a64
ci errors are related to the daemon.
I tested the PR the entire week

**Pull request merged**
