### PR TITLE
Add check height to coins panel

### LINKED ISSUE #82: gui: add height / sequence check in coins panel

### PR DESCRIPTION
**Pull request by edouardparis**
close #82

### CODE REVIEW

**Review by edouardparis — COMMENTED** [review]
Self-ACK 44d146ab2d316e2db0dbb65f095c3b8bf757399c

**Comment by darosior** [comment]
This looks nice. My suggestions:
- When a coin's timelock is expired the text should rather be "Recovery path available"
- Remove the sentence from the tile, move it to a new line in the details. In the detail either write:
  - "The recovery path will be available in X blocks"
  - "The recovery path is available"
- In the tile keep the hourglass. Either have:
  - "X <hourglass>" in black or grey when the timelocked isn't expired yet
  - "0 <hourglass>" in red when the timelocked is expired

**Comment by darosior** [comment]
Also, i don't think we should list spent coins by default (as discused in our call this morning). But let's keep that for another PR.

**Comment by darosior** [comment]
Nice! Why the minus "-" sign before the 0 though?

**Comment by edouardparis** [comment]
its a ~

**Comment by edouardparis** [comment]
2022-11-17T11:40:57,748940765+01:00

**Comment by darosior** [comment]
Oh, ok. I still think we shouldn't have it. Your latest screenshot looks good to me!

**Review by edouardparis — COMMENTED** [review]
Self-ACK 34b833f1484f1979087ad76847cc2942c06d0817

**Pull request merged**
